{"name": "Play video and verify it starts playing", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: Page.goto: NS_ERROR_CONNECTION_REFUSED\nCall log:\n  - navigating to \"http://localhost:3000/\", waiting until \"load\"", "trace": "self = <test_sanity_video_player.TestVideoSanity object at 0x000002341246B3D0>\npage = <Page url='http://localhost:3000/'>\n\n    @allure.title(\"Play video and verify it starts playing\")\n    @pytest.mark.flaky(reruns=3, reruns_delay=2)\n    def test_play_video(self, page):\n        video = VideoPage(page)\n>       video.navigate()\n\ntest_sanity_video_player.py:21: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\video_page.py:12: in navigate\n    self.page.goto(\"http://localhost:3000\")\n..\\.venv\\lib\\site-packages\\playwright\\sync_api\\_generated.py:9019: in goto\n    self._sync(\n..\\.venv\\lib\\site-packages\\playwright\\_impl\\_page.py:556: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n..\\.venv\\lib\\site-packages\\playwright\\_impl\\_frame.py:153: in goto\n    await self._channel.send(\n..\\.venv\\lib\\site-packages\\playwright\\_impl\\_connection.py:69: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x0000023412961EB0>\ncb = <function Channel.send.<locals>.<lambda> at 0x0000023412987B80>\nis_internal = False, title = None\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False, title: str = None\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(\n            task, \"__pw_stack__\", None\n        ) or inspect.stack(0)\n    \n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal, title)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.Error: Page.goto: NS_ERROR_CONNECTION_REFUSED\nE           Call log:\nE             - navigating to \"http://localhost:3000/\", waiting until \"load\"\n\n..\\.venv\\lib\\site-packages\\playwright\\_impl\\_connection.py:558: Error"}, "steps": [{"name": "Navigate to video player page", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: Page.goto: NS_ERROR_CONNECTION_REFUSED\nCall log:\n  - navigating to \"http://localhost:3000/\", waiting until \"load\"\n\n", "trace": "  File \"C:\\Users\\EladSalti\\PycharmProjects\\minute_media\\.venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\EladSalti\\PycharmProjects\\minute_media\\test\\pages\\video_page.py\", line 12, in navigate\n    self.page.goto(\"http://localhost:3000\")\n  File \"C:\\Users\\EladSalti\\PycharmProjects\\minute_media\\.venv\\lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9019, in goto\n    self._sync(\n  File \"C:\\Users\\EladSalti\\PycharmProjects\\minute_media\\.venv\\lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n  File \"C:\\Users\\EladSalti\\PycharmProjects\\minute_media\\.venv\\lib\\site-packages\\playwright\\_impl\\_page.py\", line 556, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"C:\\Users\\EladSalti\\PycharmProjects\\minute_media\\.venv\\lib\\site-packages\\playwright\\_impl\\_frame.py\", line 153, in goto\n    await self._channel.send(\n  File \"C:\\Users\\EladSalti\\PycharmProjects\\minute_media\\.venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 69, in send\n    return await self._connection.wrap_api_call(\n  File \"C:\\Users\\EladSalti\\PycharmProjects\\minute_media\\.venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 558, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1753984533861, "stop": 1753984536814}], "start": 1753984533861, "stop": 1753984536815, "uuid": "2c14dcaa-ed14-42c7-84ab-878ae9d68197", "historyId": "64b767f71dc6aa7dc0ed30a82db0d2b8", "testCaseId": "64b767f71dc6aa7dc0ed30a82db0d2b8", "fullName": "test.test_sanity_video_player.TestVideoSanity#test_play_video", "labels": [{"name": "epic", "value": "Sanity Test Suite"}, {"name": "tag", "value": "sanity"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_sanity_video_player"}, {"name": "subSuite", "value": "TestVideoSanity"}, {"name": "host", "value": "EladSalti"}, {"name": "thread", "value": "55868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_sanity_video_player"}], "titlePath": ["test", "test_sanity_video_player.py", "TestVideoSanity"]}